//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log4Net.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStringResourcePerEntityLog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public UIStringResourcePerEntityLog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Log4Net.Resources.UIStringResourcePerEntityLog", typeof(UIStringResourcePerEntityLog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Loading_Log____ {
            get {
                return ResourceManager.GetString("Loading_Log____", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Please_select_Log____ {
            get {
                return ResourceManager.GetString("Please_select_Log____", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string AddNew_Log {
            get {
                return ResourceManager.GetString("AddNew_Log", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Delete_Log {
            get {
                return ResourceManager.GetString("Delete_Log", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Details_Log {
            get {
                return ResourceManager.GetString("Details_Log", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Edit_Log {
            get {
                return ResourceManager.GetString("Edit_Log", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IdDescription {
            get {
                return ResourceManager.GetString("IdDescription", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IdRequiredErrorMessage {
            get {
                return ResourceManager.GetString("IdRequiredErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IdToolTip {
            get {
                return ResourceManager.GetString("IdToolTip", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IdValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("IdValueValidationErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IdValueValidationExpression {
            get {
                return ResourceManager.GetString("IdValueValidationExpression", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Id_is_required {
            get {
                return ResourceManager.GetString("Id_is_required", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string DateDescription {
            get {
                return ResourceManager.GetString("DateDescription", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string DateRequiredErrorMessage {
            get {
                return ResourceManager.GetString("DateRequiredErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string DateToolTip {
            get {
                return ResourceManager.GetString("DateToolTip", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string DateValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("DateValueValidationErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string DateValueValidationExpression {
            get {
                return ResourceManager.GetString("DateValueValidationExpression", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Date_is_required {
            get {
                return ResourceManager.GetString("Date_is_required", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ThreadDescription {
            get {
                return ResourceManager.GetString("ThreadDescription", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Thread {
            get {
                return ResourceManager.GetString("Thread", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ThreadRequiredErrorMessage {
            get {
                return ResourceManager.GetString("ThreadRequiredErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ThreadToolTip {
            get {
                return ResourceManager.GetString("ThreadToolTip", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ThreadValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("ThreadValueValidationErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ThreadValueValidationExpression {
            get {
                return ResourceManager.GetString("ThreadValueValidationExpression", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Thread_is_required {
            get {
                return ResourceManager.GetString("Thread_is_required", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string LevelDescription {
            get {
                return ResourceManager.GetString("LevelDescription", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string LevelRequiredErrorMessage {
            get {
                return ResourceManager.GetString("LevelRequiredErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string LevelToolTip {
            get {
                return ResourceManager.GetString("LevelToolTip", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string LevelValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("LevelValueValidationErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string LevelValueValidationExpression {
            get {
                return ResourceManager.GetString("LevelValueValidationExpression", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Level_is_required {
            get {
                return ResourceManager.GetString("Level_is_required", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string LoggerDescription {
            get {
                return ResourceManager.GetString("LoggerDescription", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Logger {
            get {
                return ResourceManager.GetString("Logger", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string LoggerRequiredErrorMessage {
            get {
                return ResourceManager.GetString("LoggerRequiredErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string LoggerToolTip {
            get {
                return ResourceManager.GetString("LoggerToolTip", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string LoggerValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("LoggerValueValidationErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string LoggerValueValidationExpression {
            get {
                return ResourceManager.GetString("LoggerValueValidationExpression", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Logger_is_required {
            get {
                return ResourceManager.GetString("Logger_is_required", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string MessageDescription {
            get {
                return ResourceManager.GetString("MessageDescription", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string MessageRequiredErrorMessage {
            get {
                return ResourceManager.GetString("MessageRequiredErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string MessageToolTip {
            get {
                return ResourceManager.GetString("MessageToolTip", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string MessageValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("MessageValueValidationErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string MessageValueValidationExpression {
            get {
                return ResourceManager.GetString("MessageValueValidationExpression", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Message_is_required {
            get {
                return ResourceManager.GetString("Message_is_required", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ExceptionDescription {
            get {
                return ResourceManager.GetString("ExceptionDescription", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ExceptionRequiredErrorMessage {
            get {
                return ResourceManager.GetString("ExceptionRequiredErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ExceptionToolTip {
            get {
                return ResourceManager.GetString("ExceptionToolTip", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ExceptionValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("ExceptionValueValidationErrorMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ExceptionValueValidationExpression {
            get {
                return ResourceManager.GetString("ExceptionValueValidationExpression", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Value_of_Log4Net_Log {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Value_of_Log4Net_Log", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Value_of_Log4Net_Log {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Value_of_Log4Net_Log", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Name_of_Log4Net_Log {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Name_of_Log4Net_Log", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Name_of_Log4Net_Log {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Name_of_Log4Net_Log", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Id_of_Log4Net_Log {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Id_of_Log4Net_Log", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Id_of_Log4Net_Log {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Id_of_Log4Net_Log", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareDateCommonOftOfCommon {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareDateCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareDateCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareDateCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareDateCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareDateCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundDateCommonOftOfCommon {
            get {
                return ResourceManager.GetString("IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundDateCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundDateCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundDateCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundDateCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundDateCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string LowerBound_ID_TextBox_Search_lowerBoundDateCommonOftOfCommon {
            get {
                return ResourceManager.GetString("LowerBound_ID_TextBox_Search_lowerBoundDateCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_LowerBound_ID_TextBox_Search_lowerBoundDateCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_LowerBound_ID_TextBox_Search_lowerBoundDateCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_LowerBound_ID_TextBox_Search_lowerBoundDateCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_LowerBound_ID_TextBox_Search_lowerBoundDateCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundDateCommonOftOfCommon {
            get {
                return ResourceManager.GetString("IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundDateCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundDateCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundDateCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundDateCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundDateCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string UpperBound_ID_TextBox_Search_upperBoundDateCommonOftOfCommon {
            get {
                return ResourceManager.GetString("UpperBound_ID_TextBox_Search_upperBoundDateCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_UpperBound_ID_TextBox_Search_upperBoundDateCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_UpperBound_ID_TextBox_Search_upperBoundDateCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_UpperBound_ID_TextBox_Search_upperBoundDateCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_UpperBound_ID_TextBox_Search_upperBoundDateCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareThreadCommonOftOfCommon {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareThreadCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareThreadCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareThreadCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareThreadCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareThreadCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ValueToBeContained_ID_TextBox_Search_valueToBeContainedThreadCommonOftOfCommon {
            get {
                return ResourceManager.GetString("ValueToBeContained_ID_TextBox_Search_valueToBeContainedThreadCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedThreadCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedThreadCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedThreadCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedThreadCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareLevelCommonOftOfCommon {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareLevelCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareLevelCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareLevelCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareLevelCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareLevelCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ValueToBeContained_ID_TextBox_Search_valueToBeContainedLevelCommonOftOfCommon {
            get {
                return ResourceManager.GetString("ValueToBeContained_ID_TextBox_Search_valueToBeContainedLevelCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedLevelCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedLevelCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedLevelCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedLevelCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareLoggerCommonOftOfCommon {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareLoggerCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareLoggerCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareLoggerCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareLoggerCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareLoggerCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ValueToBeContained_ID_TextBox_Search_valueToBeContainedLoggerCommonOftOfCommon {
            get {
                return ResourceManager.GetString("ValueToBeContained_ID_TextBox_Search_valueToBeContainedLoggerCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedLoggerCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedLoggerCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedLoggerCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedLoggerCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareMessageCommonOftOfCommon {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareMessageCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareMessageCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareMessageCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareMessageCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareMessageCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ValueToBeContained_ID_TextBox_Search_valueToBeContainedMessageCommonOftOfCommon {
            get {
                return ResourceManager.GetString("ValueToBeContained_ID_TextBox_Search_valueToBeContainedMessageCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedMessageCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedMessageCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedMessageCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedMessageCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareExceptionCommonOftOfCommon {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareExceptionCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareExceptionCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareExceptionCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareExceptionCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareExceptionCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ValueToBeContained_ID_TextBox_Search_valueToBeContainedExceptionCommonOftOfCommon {
            get {
                return ResourceManager.GetString("ValueToBeContained_ID_TextBox_Search_valueToBeContainedExceptionCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedExceptionCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedExceptionCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedExceptionCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedExceptionCommonOftOfCommon", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return ResourceManager.GetString("ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Description_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return ResourceManager.GetString("Description_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Tooltip_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier", resourceCulture);
            }
        }


    }
}