CREATE FUNCTION dbo.IPAddressToBigInteger (@IP AS VARCHAR(15))
RETURNS BIGINT
AS
BEGIN
 RETURN (CONVERT(BIGINT, PARSENAME(@IP,1)) +
         CONVERT(BIGINT, PARSENAME(@IP,2)) * 256 +
         CONVERT(BIGINT, PARSENAME(@IP,3)) * 65536 +
         CONVERT(BIGINT, PARSENAME(@IP,4)) * 16777216)
 
END