//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log4Net.Resources {
	using Windows.ApplicationModel.Resources;    
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    public class UIStringResourcePerEntityLog {
        
        private static ResourceLoader resourceLoader = new ResourceLoader("Log4Net.Resources.WinRT/UIStringResourcePerEntityLog");
        
        public UIStringResourcePerEntityLog() {
        }


        /// <summary>
        ///   Looks up a localized string similar to "Log"".
        /// </summary>
        public static string Log {
            get {
                return resourceLoader.GetString("Log");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Loading Log ..."".
        /// </summary>
        public static string Loading_Log____ {
            get {
                return resourceLoader.GetString("Loading_Log____");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Please select Log ..."".
        /// </summary>
        public static string Please_select_Log____ {
            get {
                return resourceLoader.GetString("Please_select_Log____");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "AddNew Log"".
        /// </summary>
        public static string AddNew_Log {
            get {
                return resourceLoader.GetString("AddNew_Log");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Delete Log"".
        /// </summary>
        public static string Delete_Log {
            get {
                return resourceLoader.GetString("Delete_Log");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Details Log"".
        /// </summary>
        public static string Details_Log {
            get {
                return resourceLoader.GetString("Details_Log");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Edit Log"".
        /// </summary>
        public static string Edit_Log {
            get {
                return resourceLoader.GetString("Edit_Log");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id"".
        /// </summary>
        public static string IdDescription {
            get {
                return resourceLoader.GetString("IdDescription");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id"".
        /// </summary>
        public static string Id {
            get {
                return resourceLoader.GetString("Id");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id is required"".
        /// </summary>
        public static string IdRequiredErrorMessage {
            get {
                return resourceLoader.GetString("IdRequiredErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id"".
        /// </summary>
        public static string IdToolTip {
            get {
                return resourceLoader.GetString("IdToolTip");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id has validation error"".
        /// </summary>
        public static string IdValueValidationErrorMessage {
            get {
                return resourceLoader.GetString("IdValueValidationErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Please input Id validation regular expression"".
        /// </summary>
        public static string IdValueValidationExpression {
            get {
                return resourceLoader.GetString("IdValueValidationExpression");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id is required"".
        /// </summary>
        public static string Id_is_required {
            get {
                return resourceLoader.GetString("Id_is_required");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Date"".
        /// </summary>
        public static string DateDescription {
            get {
                return resourceLoader.GetString("DateDescription");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Date"".
        /// </summary>
        public static string Date {
            get {
                return resourceLoader.GetString("Date");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Date is required"".
        /// </summary>
        public static string DateRequiredErrorMessage {
            get {
                return resourceLoader.GetString("DateRequiredErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Date"".
        /// </summary>
        public static string DateToolTip {
            get {
                return resourceLoader.GetString("DateToolTip");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Date has validation error"".
        /// </summary>
        public static string DateValueValidationErrorMessage {
            get {
                return resourceLoader.GetString("DateValueValidationErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Please input Date validation regular expression"".
        /// </summary>
        public static string DateValueValidationExpression {
            get {
                return resourceLoader.GetString("DateValueValidationExpression");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Date is required"".
        /// </summary>
        public static string Date_is_required {
            get {
                return resourceLoader.GetString("Date_is_required");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Thread"".
        /// </summary>
        public static string ThreadDescription {
            get {
                return resourceLoader.GetString("ThreadDescription");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Thread"".
        /// </summary>
        public static string Thread {
            get {
                return resourceLoader.GetString("Thread");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Thread is required"".
        /// </summary>
        public static string ThreadRequiredErrorMessage {
            get {
                return resourceLoader.GetString("ThreadRequiredErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Thread"".
        /// </summary>
        public static string ThreadToolTip {
            get {
                return resourceLoader.GetString("ThreadToolTip");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Thread has validation error"".
        /// </summary>
        public static string ThreadValueValidationErrorMessage {
            get {
                return resourceLoader.GetString("ThreadValueValidationErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Please input Thread validation regular expression"".
        /// </summary>
        public static string ThreadValueValidationExpression {
            get {
                return resourceLoader.GetString("ThreadValueValidationExpression");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Thread is required"".
        /// </summary>
        public static string Thread_is_required {
            get {
                return resourceLoader.GetString("Thread_is_required");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Level"".
        /// </summary>
        public static string LevelDescription {
            get {
                return resourceLoader.GetString("LevelDescription");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Level"".
        /// </summary>
        public static string Level {
            get {
                return resourceLoader.GetString("Level");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Level is required"".
        /// </summary>
        public static string LevelRequiredErrorMessage {
            get {
                return resourceLoader.GetString("LevelRequiredErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Level"".
        /// </summary>
        public static string LevelToolTip {
            get {
                return resourceLoader.GetString("LevelToolTip");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Level has validation error"".
        /// </summary>
        public static string LevelValueValidationErrorMessage {
            get {
                return resourceLoader.GetString("LevelValueValidationErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Please input Level validation regular expression"".
        /// </summary>
        public static string LevelValueValidationExpression {
            get {
                return resourceLoader.GetString("LevelValueValidationExpression");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Level is required"".
        /// </summary>
        public static string Level_is_required {
            get {
                return resourceLoader.GetString("Level_is_required");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Logger"".
        /// </summary>
        public static string LoggerDescription {
            get {
                return resourceLoader.GetString("LoggerDescription");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Logger"".
        /// </summary>
        public static string Logger {
            get {
                return resourceLoader.GetString("Logger");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Logger is required"".
        /// </summary>
        public static string LoggerRequiredErrorMessage {
            get {
                return resourceLoader.GetString("LoggerRequiredErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Logger"".
        /// </summary>
        public static string LoggerToolTip {
            get {
                return resourceLoader.GetString("LoggerToolTip");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Logger has validation error"".
        /// </summary>
        public static string LoggerValueValidationErrorMessage {
            get {
                return resourceLoader.GetString("LoggerValueValidationErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Please input Logger validation regular expression"".
        /// </summary>
        public static string LoggerValueValidationExpression {
            get {
                return resourceLoader.GetString("LoggerValueValidationExpression");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Logger is required"".
        /// </summary>
        public static string Logger_is_required {
            get {
                return resourceLoader.GetString("Logger_is_required");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Message"".
        /// </summary>
        public static string MessageDescription {
            get {
                return resourceLoader.GetString("MessageDescription");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Message"".
        /// </summary>
        public static string Message {
            get {
                return resourceLoader.GetString("Message");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Message is required"".
        /// </summary>
        public static string MessageRequiredErrorMessage {
            get {
                return resourceLoader.GetString("MessageRequiredErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Message"".
        /// </summary>
        public static string MessageToolTip {
            get {
                return resourceLoader.GetString("MessageToolTip");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Message has validation error"".
        /// </summary>
        public static string MessageValueValidationErrorMessage {
            get {
                return resourceLoader.GetString("MessageValueValidationErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Please input Message validation regular expression"".
        /// </summary>
        public static string MessageValueValidationExpression {
            get {
                return resourceLoader.GetString("MessageValueValidationExpression");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Message is required"".
        /// </summary>
        public static string Message_is_required {
            get {
                return resourceLoader.GetString("Message_is_required");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Exception"".
        /// </summary>
        public static string ExceptionDescription {
            get {
                return resourceLoader.GetString("ExceptionDescription");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Exception"".
        /// </summary>
        public static string Exception {
            get {
                return resourceLoader.GetString("Exception");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Exception is required"".
        /// </summary>
        public static string ExceptionRequiredErrorMessage {
            get {
                return resourceLoader.GetString("ExceptionRequiredErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Exception"".
        /// </summary>
        public static string ExceptionToolTip {
            get {
                return resourceLoader.GetString("ExceptionToolTip");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Exception has validation error"".
        /// </summary>
        public static string ExceptionValueValidationErrorMessage {
            get {
                return resourceLoader.GetString("ExceptionValueValidationErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Please input Exception validation regular expression"".
        /// </summary>
        public static string ExceptionValueValidationExpression {
            get {
                return resourceLoader.GetString("ExceptionValueValidationExpression");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value"".
        /// </summary>
        public static string Value {
            get {
                return resourceLoader.GetString("Value");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Value of Log4Net.Log"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Value_of_Log4Net_Log {
            get {
                return resourceLoader.GetString("Required_Field_Error_Message_of_property_Value_of_Log4Net_Log");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Value of Log4Net.Log"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Value_of_Log4Net_Log {
            get {
                return resourceLoader.GetString("Value_Validation_Error_Message_of_property_Value_of_Log4Net_Log");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Name"".
        /// </summary>
        public static string Name {
            get {
                return resourceLoader.GetString("Name");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Name of Log4Net.Log"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Name_of_Log4Net_Log {
            get {
                return resourceLoader.GetString("Required_Field_Error_Message_of_property_Name_of_Log4Net_Log");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Name of Log4Net.Log"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Name_of_Log4Net_Log {
            get {
                return resourceLoader.GetString("Value_Validation_Error_Message_of_property_Name_of_Log4Net_Log");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Id of Log4Net.Log"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Id_of_Log4Net_Log {
            get {
                return resourceLoader.GetString("Required_Field_Error_Message_of_property_Id_of_Log4Net_Log");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Id of Log4Net.Log"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Id_of_Log4Net_Log {
            get {
                return resourceLoader.GetString("Value_Validation_Error_Message_of_property_Id_of_Log4Net_Log");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Date"".
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareDateCommonOftOfCommon {
            get {
                return resourceLoader.GetString("IsToCompare_ID_CheckBox_Search_isToCompareDateCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Date"".
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareDateCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareDateCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Date"".
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareDateCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareDateCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "From"".
        /// </summary>
        public static string IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundDateCommonOftOfCommon {
            get {
                return resourceLoader.GetString("IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundDateCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of From"".
        /// </summary>
        public static string Description_of_IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundDateCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundDateCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of From"".
        /// </summary>
        public static string Tooltip_of_IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundDateCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_IsToCompareLowerBound_ID_CheckBox_Search_isToCompareLowerBoundDateCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "From"".
        /// </summary>
        public static string LowerBound_ID_TextBox_Search_lowerBoundDateCommonOftOfCommon {
            get {
                return resourceLoader.GetString("LowerBound_ID_TextBox_Search_lowerBoundDateCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of From"".
        /// </summary>
        public static string Description_of_LowerBound_ID_TextBox_Search_lowerBoundDateCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_LowerBound_ID_TextBox_Search_lowerBoundDateCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of From"".
        /// </summary>
        public static string Tooltip_of_LowerBound_ID_TextBox_Search_lowerBoundDateCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_LowerBound_ID_TextBox_Search_lowerBoundDateCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "To"".
        /// </summary>
        public static string IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundDateCommonOftOfCommon {
            get {
                return resourceLoader.GetString("IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundDateCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of To"".
        /// </summary>
        public static string Description_of_IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundDateCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundDateCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of To"".
        /// </summary>
        public static string Tooltip_of_IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundDateCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_IsToCompareUpperBound_ID_CheckBox_Search_isToCompareUpperBoundDateCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "To"".
        /// </summary>
        public static string UpperBound_ID_TextBox_Search_upperBoundDateCommonOftOfCommon {
            get {
                return resourceLoader.GetString("UpperBound_ID_TextBox_Search_upperBoundDateCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of To"".
        /// </summary>
        public static string Description_of_UpperBound_ID_TextBox_Search_upperBoundDateCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_UpperBound_ID_TextBox_Search_upperBoundDateCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of To"".
        /// </summary>
        public static string Tooltip_of_UpperBound_ID_TextBox_Search_upperBoundDateCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_UpperBound_ID_TextBox_Search_upperBoundDateCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Thread"".
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareThreadCommonOftOfCommon {
            get {
                return resourceLoader.GetString("IsToCompare_ID_CheckBox_Search_isToCompareThreadCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Thread"".
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareThreadCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareThreadCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Thread"".
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareThreadCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareThreadCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Thread of Log"".
        /// </summary>
        public static string ValueToBeContained_ID_TextBox_Search_valueToBeContainedThreadCommonOftOfCommon {
            get {
                return resourceLoader.GetString("ValueToBeContained_ID_TextBox_Search_valueToBeContainedThreadCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Thread of Log"".
        /// </summary>
        public static string Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedThreadCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedThreadCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Thread of Log"".
        /// </summary>
        public static string Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedThreadCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedThreadCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Level"".
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareLevelCommonOftOfCommon {
            get {
                return resourceLoader.GetString("IsToCompare_ID_CheckBox_Search_isToCompareLevelCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Level"".
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareLevelCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareLevelCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Level"".
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareLevelCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareLevelCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Level of Log"".
        /// </summary>
        public static string ValueToBeContained_ID_TextBox_Search_valueToBeContainedLevelCommonOftOfCommon {
            get {
                return resourceLoader.GetString("ValueToBeContained_ID_TextBox_Search_valueToBeContainedLevelCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Level of Log"".
        /// </summary>
        public static string Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedLevelCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedLevelCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Level of Log"".
        /// </summary>
        public static string Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedLevelCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedLevelCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Logger"".
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareLoggerCommonOftOfCommon {
            get {
                return resourceLoader.GetString("IsToCompare_ID_CheckBox_Search_isToCompareLoggerCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Logger"".
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareLoggerCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareLoggerCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Logger"".
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareLoggerCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareLoggerCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Logger of Log"".
        /// </summary>
        public static string ValueToBeContained_ID_TextBox_Search_valueToBeContainedLoggerCommonOftOfCommon {
            get {
                return resourceLoader.GetString("ValueToBeContained_ID_TextBox_Search_valueToBeContainedLoggerCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Logger of Log"".
        /// </summary>
        public static string Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedLoggerCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedLoggerCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Logger of Log"".
        /// </summary>
        public static string Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedLoggerCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedLoggerCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Message"".
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareMessageCommonOftOfCommon {
            get {
                return resourceLoader.GetString("IsToCompare_ID_CheckBox_Search_isToCompareMessageCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Message"".
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareMessageCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareMessageCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Message"".
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareMessageCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareMessageCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Message of Log"".
        /// </summary>
        public static string ValueToBeContained_ID_TextBox_Search_valueToBeContainedMessageCommonOftOfCommon {
            get {
                return resourceLoader.GetString("ValueToBeContained_ID_TextBox_Search_valueToBeContainedMessageCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Message of Log"".
        /// </summary>
        public static string Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedMessageCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedMessageCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Message of Log"".
        /// </summary>
        public static string Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedMessageCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedMessageCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Exception"".
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareExceptionCommonOftOfCommon {
            get {
                return resourceLoader.GetString("IsToCompare_ID_CheckBox_Search_isToCompareExceptionCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Exception"".
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareExceptionCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareExceptionCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Exception"".
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareExceptionCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareExceptionCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Exception of Log"".
        /// </summary>
        public static string ValueToBeContained_ID_TextBox_Search_valueToBeContainedExceptionCommonOftOfCommon {
            get {
                return resourceLoader.GetString("ValueToBeContained_ID_TextBox_Search_valueToBeContainedExceptionCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Exception of Log"".
        /// </summary>
        public static string Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedExceptionCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedExceptionCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Exception of Log"".
        /// </summary>
        public static string Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedExceptionCommonOftOfCommon {
            get {
                return resourceLoader.GetString("Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedExceptionCommonOftOfCommon");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id"".
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return resourceLoader.GetString("IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Id"".
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return resourceLoader.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Id"".
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return resourceLoader.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdByIdentifierOftOfByIdentifier");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Id of Log"".
        /// </summary>
        public static string ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return resourceLoader.GetString("ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description of Id of Log"".
        /// </summary>
        public static string Description_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return resourceLoader.GetString("Description_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Id of Log"".
        /// </summary>
        public static string Tooltip_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier {
            get {
                return resourceLoader.GetString("Tooltip_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdByIdentifierOftOfByIdentifier");
            }
        }


    }
}