//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log4Net.Resources {
	using Windows.ApplicationModel.Resources;    
    
    public class UIStringResourcePerApp {
        
        private static ResourceLoader resourceLoader = new ResourceLoader("Log4Net.Resources.WinRT/UIStringResourcePerApp");
        
        public UIStringResourcePerApp() {
        }


        /// <summary>
        ///   Looks up a localized string similar to "Log4Net"".
        /// </summary>
        public static string Application_Title {
            get {
                return resourceLoader.GetString("Application_Title");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description Of Common of Log4Net.Log"".
        /// </summary>
        public static string Description_Of_Common_of_Log4Net_Log {
            get {
                return resourceLoader.GetString("Description_Of_Common_of_Log4Net_Log");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Common of Log4Net.Log"".
        /// </summary>
        public static string Common_of_Log4Net_Log {
            get {
                return resourceLoader.GetString("Common_of_Log4Net_Log");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of Common of Log4Net.Log"".
        /// </summary>
        public static string ToolTip_Of_Common_of_Log4Net_Log {
            get {
                return resourceLoader.GetString("ToolTip_Of_Common_of_Log4Net_Log");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description Of EntityRelated of Log4Net.Log"".
        /// </summary>
        public static string Description_Of_EntityRelated_of_Log4Net_Log {
            get {
                return resourceLoader.GetString("Description_Of_EntityRelated_of_Log4Net_Log");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "EntityRelated of Log4Net.Log"".
        /// </summary>
        public static string EntityRelated_of_Log4Net_Log {
            get {
                return resourceLoader.GetString("EntityRelated_of_Log4Net_Log");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of EntityRelated of Log4Net.Log"".
        /// </summary>
        public static string ToolTip_Of_EntityRelated_of_Log4Net_Log {
            get {
                return resourceLoader.GetString("ToolTip_Of_EntityRelated_of_Log4Net_Log");
            }
        }


    }
}