//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Resources {
	using Windows.ApplicationModel.Resources;    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    public class UIStringResource {
        
        private static ResourceLoader resourceLoader = new ResourceLoader("Framework.Resources.WinRT/UIStringResource");
        
        public UIStringResource() {
        }


        /// <summary>
        ///   Looks up a localized string similar to "Change password"".
        /// </summary>
        public static string Account_ChangePassword_TitleText {
            get {
                return resourceLoader.GetString("Account_ChangePassword_TitleText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Change Password Form"".
        /// </summary>
        public static string Account_ChangePassword_LegendText {
            get {
                return resourceLoader.GetString("Account_ChangePassword_LegendText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Change password"".
        /// </summary>
        public static string Account_ChangePassword_SubmitValue {
            get {
                return resourceLoader.GetString("Account_ChangePassword_SubmitValue");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Check Availability"".
        /// </summary>
        public static string Account_CreateNewUserWizard_Button_CheckUserNameAvailabilityText {
            get {
                return resourceLoader.GetString("Account_CreateNewUserWizard_Button_CheckUserNameAvailabilityText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "This UserName is not Available, please try another one."".
        /// </summary>
        public static string Account_CreateNewUserWizard_ThisUserNameIsNotAvailableLabelText {
            get {
                return resourceLoader.GetString("Account_CreateNewUserWizard_ThisUserNameIsNotAvailableLabelText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Create New User Wizard"".
        /// </summary>
        public static string Account_CreateNewUserWizard_TitleText {
            get {
                return resourceLoader.GetString("Account_CreateNewUserWizard_TitleText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "The password provided is invalid. Please enter a valid password value."".
        /// </summary>
        public static string Account_CreateNewUserWizard_DuiplicateEmail {
            get {
                return resourceLoader.GetString("Account_CreateNewUserWizard_DuiplicateEmail");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "The password provided is invalid. Please enter a valid password value."".
        /// </summary>
        public static string Account_CreateNewUserWizard_InvalidPassword {
            get {
                return resourceLoader.GetString("Account_CreateNewUserWizard_InvalidPassword");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "The e-mail address provided is invalid. Please check the value and try again."".
        /// </summary>
        public static string Account_CreateNewUserWizard_InvalidEmail {
            get {
                return resourceLoader.GetString("Account_CreateNewUserWizard_InvalidEmail");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "The password retrieval answer provided is invalid. Please check the value and try again."".
        /// </summary>
        public static string Account_CreateNewUserWizard_InvalidAnswer {
            get {
                return resourceLoader.GetString("Account_CreateNewUserWizard_InvalidAnswer");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "The password retrieval question provided is invalid. Please check the value and try again."".
        /// </summary>
        public static string Account_CreateNewUserWizard_InvalidQuestion {
            get {
                return resourceLoader.GetString("Account_CreateNewUserWizard_InvalidQuestion");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "The user name provided is invalid. Please check the value and try again."".
        /// </summary>
        public static string Account_CreateNewUserWizard_InvalidUserName {
            get {
                return resourceLoader.GetString("Account_CreateNewUserWizard_InvalidUserName");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "The authentication provider returned an error. Please verify your entry and try again. If the problem persists, please contact your system administrator."".
        /// </summary>
        public static string Account_CreateNewUserWizard_ProviderError {
            get {
                return resourceLoader.GetString("Account_CreateNewUserWizard_ProviderError");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please contact your system administrator."".
        /// </summary>
        public static string Account_CreateNewUserWizard_UserRejected {
            get {
                return resourceLoader.GetString("Account_CreateNewUserWizard_UserRejected");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "An unknown error occurred. Please verify your entry and try again. If the problem persists, please contact your system administrator."".
        /// </summary>
        public static string Account_CreateNewUserWizard_UnknownError {
            get {
                return resourceLoader.GetString("Account_CreateNewUserWizard_UnknownError");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Log in using another service"".
        /// </summary>
        public static string Account_ExternalLogin_TitleText {
            get {
                return resourceLoader.GetString("Account_ExternalLogin_TitleText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Log in using your {0} account."".
        /// </summary>
        public static string Account_ExternalLogin_DescriptionText {
            get {
                return resourceLoader.GetString("Account_ExternalLogin_DescriptionText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "There are no external authentication services configured."".
        /// </summary>
        public static string Account_ExternalLogin_NoExternalLoginText {
            get {
                return resourceLoader.GetString("Account_ExternalLogin_NoExternalLoginText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Remove this {0} credential from your account"".
        /// </summary>
        public static string Account_ExternalLogin_RemovedExternalLoginTitle {
            get {
                return resourceLoader.GetString("Account_ExternalLogin_RemovedExternalLoginTitle");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Associate your {0} account."".
        /// </summary>
        public static string Account_ExternalLogin_AssociateExternalLoginTitle {
            get {
                return resourceLoader.GetString("Account_ExternalLogin_AssociateExternalLoginTitle");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Association Form"".
        /// </summary>
        public static string Account_ExternalLogin_AssociateExternalLoginLegend {
            get {
                return resourceLoader.GetString("Account_ExternalLogin_AssociateExternalLoginLegend");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "You've successfully authenticated with <strong>{0}</strong>. Please enter a user name for this site below and click the Confirm button to finish logging in."".
        /// </summary>
        public static string Account_ExternalLogin_AssociateExternalLoginSuccess {
            get {
                return resourceLoader.GetString("Account_ExternalLogin_AssociateExternalLoginSuccess");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Set Password Form"".
        /// </summary>
        public static string Account_ExternalLogin_SetPasswordLegend {
            get {
                return resourceLoader.GetString("Account_ExternalLogin_SetPasswordLegend");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "ou do not have a local password for this site. Add a local password so you can log in without an external login."".
        /// </summary>
        public static string Account_ExternalLogin_SetPasswordDescription {
            get {
                return resourceLoader.GetString("Account_ExternalLogin_SetPasswordDescription");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Set Password"".
        /// </summary>
        public static string Account_ExternalLogin_SetPasswordSubmitValue {
            get {
                return resourceLoader.GetString("Account_ExternalLogin_SetPasswordSubmitValue");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Login Failure"".
        /// </summary>
        public static string Account_ExternalLogin_LoginFailureTitle {
            get {
                return resourceLoader.GetString("Account_ExternalLogin_LoginFailureTitle");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Unsuccessful login with service."".
        /// </summary>
        public static string Account_ExternalLogin_LoginFailureDescription {
            get {
                return resourceLoader.GetString("Account_ExternalLogin_LoginFailureDescription");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Registered external logins."".
        /// </summary>
        public static string Account_ExternalLogin_Registeredexternallogins {
            get {
                return resourceLoader.GetString("Account_ExternalLogin_Registeredexternallogins");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Register"".
        /// </summary>
        public static string Account_ExternalLogin_AssociationTitleText {
            get {
                return resourceLoader.GetString("Account_ExternalLogin_AssociationTitleText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Register"".
        /// </summary>
        public static string Account_ExternalLogin_AssociationSubmitValue {
            get {
                return resourceLoader.GetString("Account_ExternalLogin_AssociationSubmitValue");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Your login attempt was not successful. Please try again."".
        /// </summary>
        public static string Account_LogIn_FailureText {
            get {
                return resourceLoader.GetString("Account_LogIn_FailureText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Login InstructionText"".
        /// </summary>
        public static string Account_LogIn_InstructionText {
            get {
                return resourceLoader.GetString("Account_LogIn_InstructionText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Log In"".
        /// </summary>
        public static string Account_LogIn_LoginButtonText {
            get {
                return resourceLoader.GetString("Account_LogIn_LoginButtonText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Remember me next time."".
        /// </summary>
        public static string Account_LogIn_RememberMeText {
            get {
                return resourceLoader.GetString("Account_LogIn_RememberMeText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Log In"".
        /// </summary>
        public static string Account_LogIn_TitleText {
            get {
                return resourceLoader.GetString("Account_LogIn_TitleText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Use another service to log in."".
        /// </summary>
        public static string Account_LogIn_Useanotherservicetologin {
            get {
                return resourceLoader.GetString("Account_LogIn_Useanotherservicetologin");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Use a local account to log in."".
        /// </summary>
        public static string Account_LogIn_Usealocalaccounttologin {
            get {
                return resourceLoader.GetString("Account_LogIn_Usealocalaccounttologin");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Log in Form"".
        /// </summary>
        public static string Account_LogIn_Legend {
            get {
                return resourceLoader.GetString("Account_LogIn_Legend");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "if you don't have an account."".
        /// </summary>
        public static string Account_LogIn_ifyoudonthaveanaccount {
            get {
                return resourceLoader.GetString("Account_LogIn_ifyoudonthaveanaccount");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Login"".
        /// </summary>
        public static string Account_LogInStatus_LoginText {
            get {
                return resourceLoader.GetString("Account_LogInStatus_LoginText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Logout"".
        /// </summary>
        public static string Account_LogInStatus_LogoutText {
            get {
                return resourceLoader.GetString("Account_LogInStatus_LogoutText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Manage Account"".
        /// </summary>
        public static string Account_Manage_TitleText {
            get {
                return resourceLoader.GetString("Account_Manage_TitleText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "You're logged in as "".
        /// </summary>
        public static string Account_Manage_Youreloggedinas {
            get {
                return resourceLoader.GetString("Account_Manage_Youreloggedinas");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Add an external login."".
        /// </summary>
        public static string Account_Manage_Addanexternallogin {
            get {
                return resourceLoader.GetString("Account_Manage_Addanexternallogin");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Register"".
        /// </summary>
        public static string Account_Register_TitleText {
            get {
                return resourceLoader.GetString("Account_Register_TitleText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Registration Form"".
        /// </summary>
        public static string Account_Register_Legend {
            get {
                return resourceLoader.GetString("Account_Register_Legend");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Create a new account."".
        /// </summary>
        public static string Account_Register_DescriptionText {
            get {
                return resourceLoader.GetString("Account_Register_DescriptionText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Register"".
        /// </summary>
        public static string Account_Register_SubmitValue {
            get {
                return resourceLoader.GetString("Account_Register_SubmitValue");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Your attempt to retrieve your password was not successful. Please try again."".
        /// </summary>
        public static string Account_PasswordRecovery_GeneralFailureText {
            get {
                return resourceLoader.GetString("Account_PasswordRecovery_GeneralFailureText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Your answer could not be verified. Please try again."".
        /// </summary>
        public static string Account_PasswordRecovery_QuestionFailureText {
            get {
                return resourceLoader.GetString("Account_PasswordRecovery_QuestionFailureText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Answer the following question to receive your password."".
        /// </summary>
        public static string Account_PasswordRecovery_QuestionInstructionText {
            get {
                return resourceLoader.GetString("Account_PasswordRecovery_QuestionInstructionText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Identity Confirmation"".
        /// </summary>
        public static string Account_PasswordRecovery_QuestionTitle {
            get {
                return resourceLoader.GetString("Account_PasswordRecovery_QuestionTitle");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Your password has been sent to you."".
        /// </summary>
        public static string Account_PasswordRecovery_SuccessText {
            get {
                return resourceLoader.GetString("Account_PasswordRecovery_SuccessText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Forgot Your Password"".
        /// </summary>
        public static string Account_PasswordRecovery_TitleText {
            get {
                return resourceLoader.GetString("Account_PasswordRecovery_TitleText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "We were unable to access your information. Please try again."".
        /// </summary>
        public static string Account_PasswordRecovery_UserNameFailureText {
            get {
                return resourceLoader.GetString("Account_PasswordRecovery_UserNameFailureText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Enter your User Name to receive your password."".
        /// </summary>
        public static string Account_PasswordRecovery_UserNameInstructionText {
            get {
                return resourceLoader.GetString("Account_PasswordRecovery_UserNameInstructionText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Forgot Your Password?"".
        /// </summary>
        public static string Account_PasswordRecovery_UserNameTitleText {
            get {
                return resourceLoader.GetString("Account_PasswordRecovery_UserNameTitleText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Your password has been changed."".
        /// </summary>
        public static string Account_ChangePasswordSuccess {
            get {
                return resourceLoader.GetString("Account_ChangePasswordSuccess");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Your password has been set."".
        /// </summary>
        public static string Account_SetPasswordSuccess {
            get {
                return resourceLoader.GetString("Account_SetPasswordSuccess");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "The external login was removed."".
        /// </summary>
        public static string Account_RemoveLoginSucess {
            get {
                return resourceLoader.GetString("Account_RemoveLoginSucess");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Back to List"".
        /// </summary>
        public static string BacktoList {
            get {
                return resourceLoader.GetString("BacktoList");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Answer cannot be same as Question"".
        /// </summary>
        public static string Common_AnswerErrorMessage {
            get {
                return resourceLoader.GetString("Common_AnswerErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Answer:"".
        /// </summary>
        public static string Common_AnswerLabelText {
            get {
                return resourceLoader.GetString("Common_AnswerLabelText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Answer is required."".
        /// </summary>
        public static string Common_AnswerRequiredErrorMessage {
            get {
                return resourceLoader.GetString("Common_AnswerRequiredErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Confirm Password:"".
        /// </summary>
        public static string Common_ConfirmPasswordLabelText {
            get {
                return resourceLoader.GetString("Common_ConfirmPasswordLabelText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Passwords do not match!"".
        /// </summary>
        public static string Common_ConfirmPasswordNotMatchErrorMessage {
            get {
                return resourceLoader.GetString("Common_ConfirmPasswordNotMatchErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Confirm Password is required."".
        /// </summary>
        public static string Common_ConfirmPasswordRequiredErrorMessage {
            get {
                return resourceLoader.GetString("Common_ConfirmPasswordRequiredErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Email format is not correct."".
        /// </summary>
        public static string Common_EmailFormatErrorMessage {
            get {
                return resourceLoader.GetString("Common_EmailFormatErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Email:"".
        /// </summary>
        public static string Common_EmailLabelText {
            get {
                return resourceLoader.GetString("Common_EmailLabelText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Email is required."".
        /// </summary>
        public static string Common_EmailRequiredErrorMessage {
            get {
                return resourceLoader.GetString("Common_EmailRequiredErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Current Password:"".
        /// </summary>
        public static string Common_CurrentPasswordLabelText {
            get {
                return resourceLoader.GetString("Common_CurrentPasswordLabelText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "New Password:"".
        /// </summary>
        public static string Common_NewPasswordLabelText {
            get {
                return resourceLoader.GetString("Common_NewPasswordLabelText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Password:"".
        /// </summary>
        public static string Common_PasswordLabelText {
            get {
                return resourceLoader.GetString("Common_PasswordLabelText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Password is required."".
        /// </summary>
        public static string Common_PasswordRequiredErrorMessage {
            get {
                return resourceLoader.GetString("Common_PasswordRequiredErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Password length: 6-20 characters."".
        /// </summary>
        public static string Common_PasswordLengthErrorMessage {
            get {
                return resourceLoader.GetString("Common_PasswordLengthErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "The {0} must be at least {2} characters long."".
        /// </summary>
        public static string Common_PasswordErrorMessage {
            get {
                return resourceLoader.GetString("Common_PasswordErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Question:"".
        /// </summary>
        public static string Common_QuestionLabelText {
            get {
                return resourceLoader.GetString("Common_QuestionLabelText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Question is required."".
        /// </summary>
        public static string Common_QuestionRequiredErrorMessage {
            get {
                return resourceLoader.GetString("Common_QuestionRequiredErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Submit"".
        /// </summary>
        public static string Common_SubmitButtonText {
            get {
                return resourceLoader.GetString("Common_SubmitButtonText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "User Name:"".
        /// </summary>
        public static string Common_UserNameLabelText {
            get {
                return resourceLoader.GetString("Common_UserNameLabelText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "User Name is required."".
        /// </summary>
        public static string Common_UserNameRequiredErrorMessage {
            get {
                return resourceLoader.GetString("Common_UserNameRequiredErrorMessage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Welcome to nTier on Time."".
        /// </summary>
        public static string Common_WelcomeToNTIERONTIME {
            get {
                return resourceLoader.GetString("Common_WelcomeToNTIERONTIME");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "About"".
        /// </summary>
        public static string Common_AboutPageTitle {
            get {
                return resourceLoader.GetString("Common_AboutPageTitle");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Contacts"".
        /// </summary>
        public static string Common_ContactPageTitle {
            get {
                return resourceLoader.GetString("Common_ContactPageTitle");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "No data was returned."".
        /// </summary>
        public static string Common_Nodatawasreturned {
            get {
                return resourceLoader.GetString("Common_Nodatawasreturned");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Home"".
        /// </summary>
        public static string Common_Url_Home {
            get {
                return resourceLoader.GetString("Common_Url_Home");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "About"".
        /// </summary>
        public static string Common_Url_About {
            get {
                return resourceLoader.GetString("Common_Url_About");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Contact"".
        /// </summary>
        public static string Common_Url_Contact {
            get {
                return resourceLoader.GetString("Common_Url_Contact");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Welcome"".
        /// </summary>
        public static string Common_Welcome {
            get {
                return resourceLoader.GetString("Common_Welcome");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Phone"".
        /// </summary>
        public static string Contact_PhoneText {
            get {
                return resourceLoader.GetString("Contact_PhoneText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Address"".
        /// </summary>
        public static string Contact_AddressText {
            get {
                return resourceLoader.GetString("Contact_AddressText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Email"".
        /// </summary>
        public static string Contact_EmailText {
            get {
                return resourceLoader.GetString("Contact_EmailText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Home Page"".
        /// </summary>
        public static string Home_TitleText {
            get {
                return resourceLoader.GetString("Home_TitleText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Home Page"".
        /// </summary>
        public static string Home_DescriptionText {
            get {
                return resourceLoader.GetString("Home_DescriptionText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Error"".
        /// </summary>
        public static string Error_TitleText {
            get {
                return resourceLoader.GetString("Error_TitleText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "An error occurred while processing your request."".
        /// </summary>
        public static string Error_DescriptionText {
            get {
                return resourceLoader.GetString("Error_DescriptionText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Are you sure you want to delete this?"".
        /// </summary>
        public static string Warning_Areyousureyouwanttodeletethis {
            get {
                return resourceLoader.GetString("Warning_Areyousureyouwanttodeletethis");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Workspace"".
        /// </summary>
        public static string Workspace_DescriptionText {
            get {
                return resourceLoader.GetString("Workspace_DescriptionText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "On"".
        /// </summary>
        public static string On_DescriptionText {
            get {
                return resourceLoader.GetString("On_DescriptionText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Off"".
        /// </summary>
        public static string Off_DescriptionText {
            get {
                return resourceLoader.GetString("Off_DescriptionText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Items Per Page"".
        /// </summary>
        public static string Common_Pagination_ItemsPerPage {
            get {
                return resourceLoader.GetString("Common_Pagination_ItemsPerPage");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Sort By"".
        /// </summary>
        public static string Common_Pagination_SortBy {
            get {
                return resourceLoader.GetString("Common_Pagination_SortBy");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "You can import .csv and .xlsx with first heading row in following format:"".
        /// </summary>
        public static string Data_Import_DescriptionText {
            get {
                return resourceLoader.GetString("Data_Import_DescriptionText");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Data Import Success"".
        /// </summary>
        public static string Data_Import_Success {
            get {
                return resourceLoader.GetString("Data_Import_Success");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "No Record In Source File"".
        /// </summary>
        public static string Data_Import_NoRecordInSourceFile {
            get {
                return resourceLoader.GetString("Data_Import_NoRecordInSourceFile");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "File Format or File Content is wrong"".
        /// </summary>
        public static string Data_Import_Notaproperfile {
            get {
                return resourceLoader.GetString("Data_Import_Notaproperfile");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Received"".
        /// </summary>
        public static string Received {
            get {
                return resourceLoader.GetString("Received");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Pending"".
        /// </summary>
        public static string Pending {
            get {
                return resourceLoader.GetString("Pending");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "BeingProcessed"".
        /// </summary>
        public static string BeingProcessed {
            get {
                return resourceLoader.GetString("BeingProcessed");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Rejected"".
        /// </summary>
        public static string Rejected {
            get {
                return resourceLoader.GetString("Rejected");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Accepted"".
        /// </summary>
        public static string Accepted {
            get {
                return resourceLoader.GetString("Accepted");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Succeeded"".
        /// </summary>
        public static string Succeeded {
            get {
                return resourceLoader.GetString("Succeeded");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "OnHold"".
        /// </summary>
        public static string OnHold {
            get {
                return resourceLoader.GetString("OnHold");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Failed"".
        /// </summary>
        public static string Failed {
            get {
                return resourceLoader.GetString("Failed");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Request Error"".
        /// </summary>
        public static string RequestError {
            get {
                return resourceLoader.GetString("RequestError");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Message OK"".
        /// </summary>
        public static string MessageOK {
            get {
                return resourceLoader.GetString("MessageOK");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "No Value From DataSource"".
        /// </summary>
        public static string NoValueFromDataSource {
            get {
                return resourceLoader.GetString("NoValueFromDataSource");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Message Error Detected"".
        /// </summary>
        public static string MessageErrorDetected {
            get {
                return resourceLoader.GetString("MessageErrorDetected");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "You Have No Permission To View"".
        /// </summary>
        public static string YouHaveNoPermissionToView {
            get {
                return resourceLoader.GetString("YouHaveNoPermissionToView");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "You Have NoPermissionTo Insert"".
        /// </summary>
        public static string YouHaveNoPermissionToInsert {
            get {
                return resourceLoader.GetString("YouHaveNoPermissionToInsert");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "You Have No Permission To Update"".
        /// </summary>
        public static string YouHaveNoPermissionToUpdate {
            get {
                return resourceLoader.GetString("YouHaveNoPermissionToUpdate");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "You Have No Permission To Delete"".
        /// </summary>
        public static string YouHaveNoPermissionToDelete {
            get {
                return resourceLoader.GetString("YouHaveNoPermissionToDelete");
            }
        }




		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string AddNewAlternativeText {
            get {
                return resourceLoader.GetString("AddNewAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string AddNewUrl {
            get {
                return resourceLoader.GetString("AddNewUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string AttachmentAlternativeText {
            get {
                return resourceLoader.GetString("AttachmentAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string AttachmentUrl {
            get {
                return resourceLoader.GetString("AttachmentUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string BackAlternativeText {
            get {
                return resourceLoader.GetString("BackAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string BackUrl {
            get {
                return resourceLoader.GetString("BackUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string BookmarkAlternativeText {
            get {
                return resourceLoader.GetString("BookmarkAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string BookmarkUrl {
            get {
                return resourceLoader.GetString("BookmarkUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string CalendarAlternativeText {
            get {
                return resourceLoader.GetString("CalendarAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string CalendarUrl {
            get {
                return resourceLoader.GetString("CalendarUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string CancelAlternativeText {
            get {
                return resourceLoader.GetString("CancelAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string CancelUrl {
            get {
                return resourceLoader.GetString("CancelUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ChangePasswordAlternativeText {
            get {
                return resourceLoader.GetString("ChangePasswordAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ChangePasswordUrl {
            get {
                return resourceLoader.GetString("ChangePasswordUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ChartAlternativeText {
            get {
                return resourceLoader.GetString("ChartAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ChartUrl {
            get {
                return resourceLoader.GetString("ChartUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Checkbox_CheckedAlternativeText {
            get {
                return resourceLoader.GetString("Checkbox_CheckedAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Checkbox_CheckedUrl {
            get {
                return resourceLoader.GetString("Checkbox_CheckedUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Checkbox_UncheckedAlternativeText {
            get {
                return resourceLoader.GetString("Checkbox_UncheckedAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Checkbox_UncheckedUrl {
            get {
                return resourceLoader.GetString("Checkbox_UncheckedUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ClockAlternativeText {
            get {
                return resourceLoader.GetString("ClockAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ClockUrl {
            get {
                return resourceLoader.GetString("ClockUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string CloseAlternativeText {
            get {
                return resourceLoader.GetString("CloseAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string CloseUrl {
            get {
                return resourceLoader.GetString("CloseUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string CommentAlternativeText {
            get {
                return resourceLoader.GetString("CommentAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string CommentUrl {
            get {
                return resourceLoader.GetString("CommentUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string CommentsAlternativeText {
            get {
                return resourceLoader.GetString("CommentsAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string CommentsUrl {
            get {
                return resourceLoader.GetString("CommentsUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ConfirmAlternativeText {
            get {
                return resourceLoader.GetString("ConfirmAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ConfirmUrl {
            get {
                return resourceLoader.GetString("ConfirmUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string CreateUserAlternativeText {
            get {
                return resourceLoader.GetString("CreateUserAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string CreateUserUrl {
            get {
                return resourceLoader.GetString("CreateUserUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string DeleteAlternativeText {
            get {
                return resourceLoader.GetString("DeleteAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string DeleteUrl {
            get {
                return resourceLoader.GetString("DeleteUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string DetailsAlternativeText {
            get {
                return resourceLoader.GetString("DetailsAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string DetailsUrl {
            get {
                return resourceLoader.GetString("DetailsUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string DownAlternativeText {
            get {
                return resourceLoader.GetString("DownAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string DownUrl {
            get {
                return resourceLoader.GetString("DownUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string DownloadAlternativeText {
            get {
                return resourceLoader.GetString("DownloadAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string DownloadUrl {
            get {
                return resourceLoader.GetString("DownloadUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string EditAlternativeText {
            get {
                return resourceLoader.GetString("EditAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string EditUrl {
            get {
                return resourceLoader.GetString("EditUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ExitAlternativeText {
            get {
                return resourceLoader.GetString("ExitAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ExitUrl {
            get {
                return resourceLoader.GetString("ExitUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ExportAlternativeText {
            get {
                return resourceLoader.GetString("ExportAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ExportUrl {
            get {
                return resourceLoader.GetString("ExportUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ExportToExcelAlternativeText {
            get {
                return resourceLoader.GetString("ExportToExcelAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ExportToExcelUrl {
            get {
                return resourceLoader.GetString("ExportToExcelUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string FavoriteAlternativeText {
            get {
                return resourceLoader.GetString("FavoriteAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string FavoriteUrl {
            get {
                return resourceLoader.GetString("FavoriteUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string FileReplaceAlternativeText {
            get {
                return resourceLoader.GetString("FileReplaceAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string FileReplaceUrl {
            get {
                return resourceLoader.GetString("FileReplaceUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string FirstAlternativeText {
            get {
                return resourceLoader.GetString("FirstAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string FirstUrl {
            get {
                return resourceLoader.GetString("FirstUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ForwardAlternativeText {
            get {
                return resourceLoader.GetString("ForwardAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ForwardUrl {
            get {
                return resourceLoader.GetString("ForwardUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string GoAlternativeText {
            get {
                return resourceLoader.GetString("GoAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string GoUrl {
            get {
                return resourceLoader.GetString("GoUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string HeartAlternativeText {
            get {
                return resourceLoader.GetString("HeartAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string HeartUrl {
            get {
                return resourceLoader.GetString("HeartUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string HelpAlternativeText {
            get {
                return resourceLoader.GetString("HelpAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string HelpUrl {
            get {
                return resourceLoader.GetString("HelpUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string HomeAlternativeText {
            get {
                return resourceLoader.GetString("HomeAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string HomeUrl {
            get {
                return resourceLoader.GetString("HomeUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ImportAlternativeText {
            get {
                return resourceLoader.GetString("ImportAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ImportUrl {
            get {
                return resourceLoader.GetString("ImportUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IndexAlternativeText {
            get {
                return resourceLoader.GetString("IndexAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string IndexUrl {
            get {
                return resourceLoader.GetString("IndexUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string InformationAlternativeText {
            get {
                return resourceLoader.GetString("InformationAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string InformationUrl {
            get {
                return resourceLoader.GetString("InformationUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string InsertAlternativeText {
            get {
                return resourceLoader.GetString("InsertAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string InsertUrl {
            get {
                return resourceLoader.GetString("InsertUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string LastAlternativeText {
            get {
                return resourceLoader.GetString("LastAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string LastUrl {
            get {
                return resourceLoader.GetString("LastUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string LoadFileAlternativeText {
            get {
                return resourceLoader.GetString("LoadFileAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string LoadFileUrl {
            get {
                return resourceLoader.GetString("LoadFileUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string LockAlternativeText {
            get {
                return resourceLoader.GetString("LockAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string LockUrl {
            get {
                return resourceLoader.GetString("LockUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string MailAlternativeText {
            get {
                return resourceLoader.GetString("MailAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string MailUrl {
            get {
                return resourceLoader.GetString("MailUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string MailLockAlternativeText {
            get {
                return resourceLoader.GetString("MailLockAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string MailLockUrl {
            get {
                return resourceLoader.GetString("MailLockUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string MailReceiveAlternativeText {
            get {
                return resourceLoader.GetString("MailReceiveAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string MailReceiveUrl {
            get {
                return resourceLoader.GetString("MailReceiveUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string MailSearchAlternativeText {
            get {
                return resourceLoader.GetString("MailSearchAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string MailSearchUrl {
            get {
                return resourceLoader.GetString("MailSearchUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string MailSendAlternativeText {
            get {
                return resourceLoader.GetString("MailSendAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string MailSendUrl {
            get {
                return resourceLoader.GetString("MailSendUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string MinusAlternativeText {
            get {
                return resourceLoader.GetString("MinusAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string MinusUrl {
            get {
                return resourceLoader.GetString("MinusUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string MoneyAlternativeText {
            get {
                return resourceLoader.GetString("MoneyAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string MoneyUrl {
            get {
                return resourceLoader.GetString("MoneyUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string NewFileAlternativeText {
            get {
                return resourceLoader.GetString("NewFileAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string NewFileUrl {
            get {
                return resourceLoader.GetString("NewFileUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string NextAlternativeText {
            get {
                return resourceLoader.GetString("NextAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string NextUrl {
            get {
                return resourceLoader.GetString("NextUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string NumericDownAlternativeText {
            get {
                return resourceLoader.GetString("NumericDownAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string NumericDownUrl {
            get {
                return resourceLoader.GetString("NumericDownUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string NumericUpAlternativeText {
            get {
                return resourceLoader.GetString("NumericUpAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string NumericUpUrl {
            get {
                return resourceLoader.GetString("NumericUpUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string OpenAlternativeText {
            get {
                return resourceLoader.GetString("OpenAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string OpenUrl {
            get {
                return resourceLoader.GetString("OpenUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string PageSizeAlternativeText {
            get {
                return resourceLoader.GetString("PageSizeAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string PageSizeUrl {
            get {
                return resourceLoader.GetString("PageSizeUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string PasswordRecoveryAlternativeText {
            get {
                return resourceLoader.GetString("PasswordRecoveryAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string PasswordRecoveryUrl {
            get {
                return resourceLoader.GetString("PasswordRecoveryUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string PauseAlternativeText {
            get {
                return resourceLoader.GetString("PauseAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string PauseUrl {
            get {
                return resourceLoader.GetString("PauseUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string PieChartAlternativeText {
            get {
                return resourceLoader.GetString("PieChartAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string PieChartUrl {
            get {
                return resourceLoader.GetString("PieChartUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string PlayAlternativeText {
            get {
                return resourceLoader.GetString("PlayAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string PlayUrl {
            get {
                return resourceLoader.GetString("PlayUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string PlusAlternativeText {
            get {
                return resourceLoader.GetString("PlusAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string PlusUrl {
            get {
                return resourceLoader.GetString("PlusUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string PreviousAlternativeText {
            get {
                return resourceLoader.GetString("PreviousAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string PreviousUrl {
            get {
                return resourceLoader.GetString("PreviousUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ProcessAlternativeText {
            get {
                return resourceLoader.GetString("ProcessAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ProcessUrl {
            get {
                return resourceLoader.GetString("ProcessUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string PromotionAlternativeText {
            get {
                return resourceLoader.GetString("PromotionAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string PromotionUrl {
            get {
                return resourceLoader.GetString("PromotionUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ProtectionAlternativeText {
            get {
                return resourceLoader.GetString("ProtectionAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ProtectionUrl {
            get {
                return resourceLoader.GetString("ProtectionUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string QuestionAlternativeText {
            get {
                return resourceLoader.GetString("QuestionAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string QuestionUrl {
            get {
                return resourceLoader.GetString("QuestionUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string RecordAlternativeText {
            get {
                return resourceLoader.GetString("RecordAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string RecordUrl {
            get {
                return resourceLoader.GetString("RecordUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string RecycleAlternativeText {
            get {
                return resourceLoader.GetString("RecycleAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string RecycleUrl {
            get {
                return resourceLoader.GetString("RecycleUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string RedoAlternativeText {
            get {
                return resourceLoader.GetString("RedoAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string RedoUrl {
            get {
                return resourceLoader.GetString("RedoUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string RefreshAlternativeText {
            get {
                return resourceLoader.GetString("RefreshAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string RefreshUrl {
            get {
                return resourceLoader.GetString("RefreshUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string RegisterAlternativeText {
            get {
                return resourceLoader.GetString("RegisterAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string RegisterUrl {
            get {
                return resourceLoader.GetString("RegisterUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string RepeatAlternativeText {
            get {
                return resourceLoader.GetString("RepeatAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string RepeatUrl {
            get {
                return resourceLoader.GetString("RepeatUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string RSSAlternativeText {
            get {
                return resourceLoader.GetString("RSSAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string RSSUrl {
            get {
                return resourceLoader.GetString("RSSUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string SaveAlternativeText {
            get {
                return resourceLoader.GetString("SaveAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string SaveUrl {
            get {
                return resourceLoader.GetString("SaveUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string SearchAlternativeText {
            get {
                return resourceLoader.GetString("SearchAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string SearchUrl {
            get {
                return resourceLoader.GetString("SearchUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string SearchPageAlternativeText {
            get {
                return resourceLoader.GetString("SearchPageAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string SearchPageUrl {
            get {
                return resourceLoader.GetString("SearchPageUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string SettingAlternativeText {
            get {
                return resourceLoader.GetString("SettingAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string SettingUrl {
            get {
                return resourceLoader.GetString("SettingUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ShoppingCartAlternativeText {
            get {
                return resourceLoader.GetString("ShoppingCartAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ShoppingCartUrl {
            get {
                return resourceLoader.GetString("ShoppingCartUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string SignUpAlternativeText {
            get {
                return resourceLoader.GetString("SignUpAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string SignUpUrl {
            get {
                return resourceLoader.GetString("SignUpUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string StopAlternativeText {
            get {
                return resourceLoader.GetString("StopAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string StopUrl {
            get {
                return resourceLoader.GetString("StopUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string TagBlueAlternativeText {
            get {
                return resourceLoader.GetString("TagBlueAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string TagBlueUrl {
            get {
                return resourceLoader.GetString("TagBlueUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string TagGreenAlternativeText {
            get {
                return resourceLoader.GetString("TagGreenAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string TagGreenUrl {
            get {
                return resourceLoader.GetString("TagGreenUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string TextPageAlternativeText {
            get {
                return resourceLoader.GetString("TextPageAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string TextPageUrl {
            get {
                return resourceLoader.GetString("TextPageUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string TitleAlternativeText {
            get {
                return resourceLoader.GetString("TitleAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string TitleUrl {
            get {
                return resourceLoader.GetString("TitleUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ToggleButton_CheckedAlternativeText {
            get {
                return resourceLoader.GetString("ToggleButton_CheckedAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ToggleButton_CheckedUrl {
            get {
                return resourceLoader.GetString("ToggleButton_CheckedUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ToggleButton_UncheckedAlternativeText {
            get {
                return resourceLoader.GetString("ToggleButton_UncheckedAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ToggleButton_UncheckedUrl {
            get {
                return resourceLoader.GetString("ToggleButton_UncheckedUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string TutorialAlternativeText {
            get {
                return resourceLoader.GetString("TutorialAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string TutorialUrl {
            get {
                return resourceLoader.GetString("TutorialUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string UndoAlternativeText {
            get {
                return resourceLoader.GetString("UndoAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string UndoUrl {
            get {
                return resourceLoader.GetString("UndoUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string UnlockAlternativeText {
            get {
                return resourceLoader.GetString("UnlockAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string UnlockUrl {
            get {
                return resourceLoader.GetString("UnlockUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string UpAlternativeText {
            get {
                return resourceLoader.GetString("UpAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string UpUrl {
            get {
                return resourceLoader.GetString("UpUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string UpdateAlternativeText {
            get {
                return resourceLoader.GetString("UpdateAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string UpdateUrl {
            get {
                return resourceLoader.GetString("UpdateUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string UserAlternativeText {
            get {
                return resourceLoader.GetString("UserAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string UserUrl {
            get {
                return resourceLoader.GetString("UserUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string UsersAlternativeText {
            get {
                return resourceLoader.GetString("UsersAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string UsersUrl {
            get {
                return resourceLoader.GetString("UsersUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string WarningAlternativeText {
            get {
                return resourceLoader.GetString("WarningAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string WarningUrl {
            get {
                return resourceLoader.GetString("WarningUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ZoomInAlternativeText {
            get {
                return resourceLoader.GetString("ZoomInAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ZoomInUrl {
            get {
                return resourceLoader.GetString("ZoomInUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ZoomOutAlternativeText {
            get {
                return resourceLoader.GetString("ZoomOutAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string ZoomOutUrl {
            get {
                return resourceLoader.GetString("ZoomOutUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string CopyAlternativeText {
            get {
                return resourceLoader.GetString("CopyAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string CopyUrl {
            get {
                return resourceLoader.GetString("CopyUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string PasteAlternativeText {
            get {
                return resourceLoader.GetString("PasteAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string PasteUrl {
            get {
                return resourceLoader.GetString("PasteUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string MoreAlternativeText {
            get {
                return resourceLoader.GetString("MoreAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string MoreUrl {
            get {
                return resourceLoader.GetString("MoreUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string FullDetailsAlternativeText {
            get {
                return resourceLoader.GetString("FullDetailsAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string FullDetailsUrl {
            get {
                return resourceLoader.GetString("FullDetailsUrl");
            }
        }



		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string GotoSearchAlternativeText {
            get {
                return resourceLoader.GetString("GotoSearchAlternativeText");
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string GotoSearchUrl {
            get {
                return resourceLoader.GetString("GotoSearchUrl");
            }
        }




    }
}