//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Resx {
    using System;
    using System.Reflection;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStringResource {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public UIStringResource() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Resx.UIStringResource", typeof(UIStringResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Change password"".
        /// </summary>
        public static string Account_ChangePassword_TitleText {
            get {
                return ResourceManager.GetString("Account_ChangePassword_TitleText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Change Password Form"".
        /// </summary>
        public static string Account_ChangePassword_LegendText {
            get {
                return ResourceManager.GetString("Account_ChangePassword_LegendText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Change password"".
        /// </summary>
        public static string Account_ChangePassword_SubmitValue {
            get {
                return ResourceManager.GetString("Account_ChangePassword_SubmitValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Check Availability"".
        /// </summary>
        public static string Account_CreateNewUserWizard_Button_CheckUserNameAvailabilityText {
            get {
                return ResourceManager.GetString("Account_CreateNewUserWizard_Button_CheckUserNameAvailabilityText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "This UserName is not Available, please try another one."".
        /// </summary>
        public static string Account_CreateNewUserWizard_ThisUserNameIsNotAvailableLabelText {
            get {
                return ResourceManager.GetString("Account_CreateNewUserWizard_ThisUserNameIsNotAvailableLabelText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Create New User Wizard"".
        /// </summary>
        public static string Account_CreateNewUserWizard_TitleText {
            get {
                return ResourceManager.GetString("Account_CreateNewUserWizard_TitleText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The password provided is invalid. Please enter a valid password value."".
        /// </summary>
        public static string Account_CreateNewUserWizard_DuiplicateEmail {
            get {
                return ResourceManager.GetString("Account_CreateNewUserWizard_DuiplicateEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The password provided is invalid. Please enter a valid password value."".
        /// </summary>
        public static string Account_CreateNewUserWizard_InvalidPassword {
            get {
                return ResourceManager.GetString("Account_CreateNewUserWizard_InvalidPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The e-mail address provided is invalid. Please check the value and try again."".
        /// </summary>
        public static string Account_CreateNewUserWizard_InvalidEmail {
            get {
                return ResourceManager.GetString("Account_CreateNewUserWizard_InvalidEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The password retrieval answer provided is invalid. Please check the value and try again."".
        /// </summary>
        public static string Account_CreateNewUserWizard_InvalidAnswer {
            get {
                return ResourceManager.GetString("Account_CreateNewUserWizard_InvalidAnswer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The password retrieval question provided is invalid. Please check the value and try again."".
        /// </summary>
        public static string Account_CreateNewUserWizard_InvalidQuestion {
            get {
                return ResourceManager.GetString("Account_CreateNewUserWizard_InvalidQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The user name provided is invalid. Please check the value and try again."".
        /// </summary>
        public static string Account_CreateNewUserWizard_InvalidUserName {
            get {
                return ResourceManager.GetString("Account_CreateNewUserWizard_InvalidUserName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The authentication provider returned an error. Please verify your entry and try again. If the problem persists, please contact your system administrator."".
        /// </summary>
        public static string Account_CreateNewUserWizard_ProviderError {
            get {
                return ResourceManager.GetString("Account_CreateNewUserWizard_ProviderError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please contact your system administrator."".
        /// </summary>
        public static string Account_CreateNewUserWizard_UserRejected {
            get {
                return ResourceManager.GetString("Account_CreateNewUserWizard_UserRejected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "An unknown error occurred. Please verify your entry and try again. If the problem persists, please contact your system administrator."".
        /// </summary>
        public static string Account_CreateNewUserWizard_UnknownError {
            get {
                return ResourceManager.GetString("Account_CreateNewUserWizard_UnknownError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Log in using another service"".
        /// </summary>
        public static string Account_ExternalLogin_TitleText {
            get {
                return ResourceManager.GetString("Account_ExternalLogin_TitleText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Log in using your {0} account."".
        /// </summary>
        public static string Account_ExternalLogin_DescriptionText {
            get {
                return ResourceManager.GetString("Account_ExternalLogin_DescriptionText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "There are no external authentication services configured."".
        /// </summary>
        public static string Account_ExternalLogin_NoExternalLoginText {
            get {
                return ResourceManager.GetString("Account_ExternalLogin_NoExternalLoginText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Remove this {0} credential from your account"".
        /// </summary>
        public static string Account_ExternalLogin_RemovedExternalLoginTitle {
            get {
                return ResourceManager.GetString("Account_ExternalLogin_RemovedExternalLoginTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Associate your {0} account."".
        /// </summary>
        public static string Account_ExternalLogin_AssociateExternalLoginTitle {
            get {
                return ResourceManager.GetString("Account_ExternalLogin_AssociateExternalLoginTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Association Form"".
        /// </summary>
        public static string Account_ExternalLogin_AssociateExternalLoginLegend {
            get {
                return ResourceManager.GetString("Account_ExternalLogin_AssociateExternalLoginLegend", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "You've successfully authenticated with <strong>{0}</strong>. Please enter a user name for this site below and click the Confirm button to finish logging in."".
        /// </summary>
        public static string Account_ExternalLogin_AssociateExternalLoginSuccess {
            get {
                return ResourceManager.GetString("Account_ExternalLogin_AssociateExternalLoginSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Set Password Form"".
        /// </summary>
        public static string Account_ExternalLogin_SetPasswordLegend {
            get {
                return ResourceManager.GetString("Account_ExternalLogin_SetPasswordLegend", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ou do not have a local password for this site. Add a local password so you can log in without an external login."".
        /// </summary>
        public static string Account_ExternalLogin_SetPasswordDescription {
            get {
                return ResourceManager.GetString("Account_ExternalLogin_SetPasswordDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Set Password"".
        /// </summary>
        public static string Account_ExternalLogin_SetPasswordSubmitValue {
            get {
                return ResourceManager.GetString("Account_ExternalLogin_SetPasswordSubmitValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Login Failure"".
        /// </summary>
        public static string Account_ExternalLogin_LoginFailureTitle {
            get {
                return ResourceManager.GetString("Account_ExternalLogin_LoginFailureTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Unsuccessful login with service."".
        /// </summary>
        public static string Account_ExternalLogin_LoginFailureDescription {
            get {
                return ResourceManager.GetString("Account_ExternalLogin_LoginFailureDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Registered external logins."".
        /// </summary>
        public static string Account_ExternalLogin_Registeredexternallogins {
            get {
                return ResourceManager.GetString("Account_ExternalLogin_Registeredexternallogins", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Register"".
        /// </summary>
        public static string Account_ExternalLogin_AssociationTitleText {
            get {
                return ResourceManager.GetString("Account_ExternalLogin_AssociationTitleText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Register"".
        /// </summary>
        public static string Account_ExternalLogin_AssociationSubmitValue {
            get {
                return ResourceManager.GetString("Account_ExternalLogin_AssociationSubmitValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Your login attempt was not successful. Please try again."".
        /// </summary>
        public static string Account_LogIn_FailureText {
            get {
                return ResourceManager.GetString("Account_LogIn_FailureText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Login InstructionText"".
        /// </summary>
        public static string Account_LogIn_InstructionText {
            get {
                return ResourceManager.GetString("Account_LogIn_InstructionText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Log In"".
        /// </summary>
        public static string Account_LogIn_LoginButtonText {
            get {
                return ResourceManager.GetString("Account_LogIn_LoginButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Remember me next time."".
        /// </summary>
        public static string Account_LogIn_RememberMeText {
            get {
                return ResourceManager.GetString("Account_LogIn_RememberMeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Log In"".
        /// </summary>
        public static string Account_LogIn_TitleText {
            get {
                return ResourceManager.GetString("Account_LogIn_TitleText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Use another service to log in."".
        /// </summary>
        public static string Account_LogIn_Useanotherservicetologin {
            get {
                return ResourceManager.GetString("Account_LogIn_Useanotherservicetologin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Use a local account to log in."".
        /// </summary>
        public static string Account_LogIn_Usealocalaccounttologin {
            get {
                return ResourceManager.GetString("Account_LogIn_Usealocalaccounttologin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Log in Form"".
        /// </summary>
        public static string Account_LogIn_Legend {
            get {
                return ResourceManager.GetString("Account_LogIn_Legend", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "if you don't have an account."".
        /// </summary>
        public static string Account_LogIn_ifyoudonthaveanaccount {
            get {
                return ResourceManager.GetString("Account_LogIn_ifyoudonthaveanaccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Login"".
        /// </summary>
        public static string Account_LogInStatus_LoginText {
            get {
                return ResourceManager.GetString("Account_LogInStatus_LoginText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Logout"".
        /// </summary>
        public static string Account_LogInStatus_LogoutText {
            get {
                return ResourceManager.GetString("Account_LogInStatus_LogoutText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Manage Account"".
        /// </summary>
        public static string Account_Manage_TitleText {
            get {
                return ResourceManager.GetString("Account_Manage_TitleText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "You're logged in as "".
        /// </summary>
        public static string Account_Manage_Youreloggedinas {
            get {
                return ResourceManager.GetString("Account_Manage_Youreloggedinas", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Add an external login."".
        /// </summary>
        public static string Account_Manage_Addanexternallogin {
            get {
                return ResourceManager.GetString("Account_Manage_Addanexternallogin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Register"".
        /// </summary>
        public static string Account_Register_TitleText {
            get {
                return ResourceManager.GetString("Account_Register_TitleText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Registration Form"".
        /// </summary>
        public static string Account_Register_Legend {
            get {
                return ResourceManager.GetString("Account_Register_Legend", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Create a new account."".
        /// </summary>
        public static string Account_Register_DescriptionText {
            get {
                return ResourceManager.GetString("Account_Register_DescriptionText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Register"".
        /// </summary>
        public static string Account_Register_SubmitValue {
            get {
                return ResourceManager.GetString("Account_Register_SubmitValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Your attempt to retrieve your password was not successful. Please try again."".
        /// </summary>
        public static string Account_PasswordRecovery_GeneralFailureText {
            get {
                return ResourceManager.GetString("Account_PasswordRecovery_GeneralFailureText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Your answer could not be verified. Please try again."".
        /// </summary>
        public static string Account_PasswordRecovery_QuestionFailureText {
            get {
                return ResourceManager.GetString("Account_PasswordRecovery_QuestionFailureText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Answer the following question to receive your password."".
        /// </summary>
        public static string Account_PasswordRecovery_QuestionInstructionText {
            get {
                return ResourceManager.GetString("Account_PasswordRecovery_QuestionInstructionText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Identity Confirmation"".
        /// </summary>
        public static string Account_PasswordRecovery_QuestionTitle {
            get {
                return ResourceManager.GetString("Account_PasswordRecovery_QuestionTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Your password has been sent to you."".
        /// </summary>
        public static string Account_PasswordRecovery_SuccessText {
            get {
                return ResourceManager.GetString("Account_PasswordRecovery_SuccessText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Forgot Your Password"".
        /// </summary>
        public static string Account_PasswordRecovery_TitleText {
            get {
                return ResourceManager.GetString("Account_PasswordRecovery_TitleText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "We were unable to access your information. Please try again."".
        /// </summary>
        public static string Account_PasswordRecovery_UserNameFailureText {
            get {
                return ResourceManager.GetString("Account_PasswordRecovery_UserNameFailureText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Enter your User Name to receive your password."".
        /// </summary>
        public static string Account_PasswordRecovery_UserNameInstructionText {
            get {
                return ResourceManager.GetString("Account_PasswordRecovery_UserNameInstructionText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Forgot Your Password?"".
        /// </summary>
        public static string Account_PasswordRecovery_UserNameTitleText {
            get {
                return ResourceManager.GetString("Account_PasswordRecovery_UserNameTitleText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Your password has been changed."".
        /// </summary>
        public static string Account_ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("Account_ChangePasswordSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Your password has been set."".
        /// </summary>
        public static string Account_SetPasswordSuccess {
            get {
                return ResourceManager.GetString("Account_SetPasswordSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The external login was removed."".
        /// </summary>
        public static string Account_RemoveLoginSucess {
            get {
                return ResourceManager.GetString("Account_RemoveLoginSucess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "You're logged in as "".
        /// </summary>
        public static string Account__ChangePasswordPartial_Youreloggedinas {
            get {
                return ResourceManager.GetString("Account__ChangePasswordPartial_Youreloggedinas", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Change Password Form "".
        /// </summary>
        public static string Account__ChangePasswordPartial_Description {
            get {
                return ResourceManager.GetString("Account__ChangePasswordPartial_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Change password"".
        /// </summary>
        public static string Account__ChangePasswordPartial_SubmitValue {
            get {
                return ResourceManager.GetString("Account__ChangePasswordPartial_SubmitValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Use another service to log in."".
        /// </summary>
        public static string Account__ExternalLoginsListPartial_Useanotherservicetologin {
            get {
                return ResourceManager.GetString("Account__ExternalLoginsListPartial_Useanotherservicetologin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "There are no external authentication services configured. See <a href="http://go.microsoft.com/fwlink/?LinkId=313242">this article</a> for details on setting up this ASP.NET application to support logging in via external services."".
        /// </summary>
        public static string Account__ExternalLoginsListPartial_Description {
            get {
                return ResourceManager.GetString("Account__ExternalLoginsListPartial_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Log in using your account as ."".
        /// </summary>
        public static string Account__ExternalLoginsListPartial_Loginusingyouraccountas {
            get {
                return ResourceManager.GetString("Account__ExternalLoginsListPartial_Loginusingyouraccountas", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Registered Logins"".
        /// </summary>
        public static string Account__RemoveAccountPartial_Title {
            get {
                return ResourceManager.GetString("Account__RemoveAccountPartial_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Remove login from your account:"".
        /// </summary>
        public static string Account__RemoveAccountPartial_ButtonText {
            get {
                return ResourceManager.GetString("Account__RemoveAccountPartial_ButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "You do not have a local username/password for this site. Add a local account so you can log in without an external login."".
        /// </summary>
        public static string Account__SetPasswordPartial_Description {
            get {
                return ResourceManager.GetString("Account__SetPasswordPartial_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Create Local Login"".
        /// </summary>
        public static string Account__SetPasswordPartial_Title {
            get {
                return ResourceManager.GetString("Account__SetPasswordPartial_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Set password"".
        /// </summary>
        public static string Account__SetPasswordPartial_SubmitValue {
            get {
                return ResourceManager.GetString("Account__SetPasswordPartial_SubmitValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Confirm Account"".
        /// </summary>
        public static string Account_ConfirmEmail_ConfirmAccount {
            get {
                return ResourceManager.GetString("Account_ConfirmEmail_ConfirmAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Thank you for confirming your account. Please"".
        /// </summary>
        public static string Account_ConfirmEmail_ThankyouforconfirmingyouraccountPlease {
            get {
                return ResourceManager.GetString("Account_ConfirmEmail_ThankyouforconfirmingyouraccountPlease", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Click Here To Log In"".
        /// </summary>
        public static string Account_ConfirmEmail_ClickHereToLogIn {
            get {
                return ResourceManager.GetString("Account_ConfirmEmail_ClickHereToLogIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Register"".
        /// </summary>
        public static string Account_ExternalLoginConfirmation_Title {
            get {
                return ResourceManager.GetString("Account_ExternalLoginConfirmation_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "You've successfully authenticated with "".
        /// </summary>
        public static string Account_ExternalLoginConfirmation_SuccessDescripionPart1 {
            get {
                return ResourceManager.GetString("Account_ExternalLoginConfirmation_SuccessDescripionPart1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Please enter a user name for this site below and click the Register button to finish logging in. "".
        /// </summary>
        public static string Account_ExternalLoginConfirmation_SuccessDescripionPart2 {
            get {
                return ResourceManager.GetString("Account_ExternalLoginConfirmation_SuccessDescripionPart2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Associate your account of "".
        /// </summary>
        public static string Account_ExternalLoginConfirmation_Associateyouraccountof {
            get {
                return ResourceManager.GetString("Account_ExternalLoginConfirmation_Associateyouraccountof", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Register"".
        /// </summary>
        public static string Account_ExternalLoginConfirmation_SubmitValue {
            get {
                return ResourceManager.GetString("Account_ExternalLoginConfirmation_SubmitValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Unsuccessful login with service."".
        /// </summary>
        public static string Account_ExternalLoginFailure_Description {
            get {
                return ResourceManager.GetString("Account_ExternalLoginFailure_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Login Failure"".
        /// </summary>
        public static string Account_ExternalLoginFailure_Title {
            get {
                return ResourceManager.GetString("Account_ExternalLoginFailure_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Forget your email."".
        /// </summary>
        public static string Account_ForgotPassword_Title {
            get {
                return ResourceManager.GetString("Account_ForgotPassword_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Enter your email."".
        /// </summary>
        public static string Account_ForgotPassword_Description {
            get {
                return ResourceManager.GetString("Account_ForgotPassword_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Continue."".
        /// </summary>
        public static string Account_ForgotPassword_SubmitValue {
            get {
                return ResourceManager.GetString("Account_ForgotPassword_SubmitValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Please check your email to reset your password."".
        /// </summary>
        public static string Account_ForgotPasswordConfirmation_Description {
            get {
                return ResourceManager.GetString("Account_ForgotPasswordConfirmation_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Forgot Password Confirmation"".
        /// </summary>
        public static string Account_ForgotPasswordConfirmation_Title {
            get {
                return ResourceManager.GetString("Account_ForgotPasswordConfirmation_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Register as a new user"".
        /// </summary>
        public static string Account_LogIn_Registerasanewuser {
            get {
                return ResourceManager.GetString("Account_LogIn_Registerasanewuser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Enable this once you have account confirmation enabled for password reset functionality"".
        /// </summary>
        public static string Account_LogIn_Enablethisonceyouhaveaccountconfirmationenabledforpasswordresetfunctionality {
            get {
                return ResourceManager.GetString("Account_LogIn_Enablethisonceyouhaveaccountconfirmationenabledforpasswordresetfunctionality", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Use a local account to log in."".
        /// </summary>
        public static string Account_LogIn_Description {
            get {
                return ResourceManager.GetString("Account_LogIn_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Reset password"".
        /// </summary>
        public static string Account_ResetPassword_Title {
            get {
                return ResourceManager.GetString("Account_ResetPassword_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Reset your password."".
        /// </summary>
        public static string Account_ResetPassword_Description {
            get {
                return ResourceManager.GetString("Account_ResetPassword_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Reset"".
        /// </summary>
        public static string Account_ResetPassword_SubmitValue {
            get {
                return ResourceManager.GetString("Account_ResetPassword_SubmitValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Reset password confirmation"".
        /// </summary>
        public static string Account_ResetPasswordConfirmation_Title {
            get {
                return ResourceManager.GetString("Account_ResetPasswordConfirmation_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Your password has been reset. Please "".
        /// </summary>
        public static string Account_ResetPasswordConfirmation_Description {
            get {
                return ResourceManager.GetString("Account_ResetPasswordConfirmation_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "click here to log in"".
        /// </summary>
        public static string Account_ResetPasswordConfirmation_clickheretologin {
            get {
                return ResourceManager.GetString("Account_ResetPasswordConfirmation_clickheretologin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Back to List"".
        /// </summary>
        public static string BacktoList {
            get {
                return ResourceManager.GetString("BacktoList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Answer cannot be same as Question"".
        /// </summary>
        public static string Common_AnswerErrorMessage {
            get {
                return ResourceManager.GetString("Common_AnswerErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Answer:"".
        /// </summary>
        public static string Common_AnswerLabelText {
            get {
                return ResourceManager.GetString("Common_AnswerLabelText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Answer is required."".
        /// </summary>
        public static string Common_AnswerRequiredErrorMessage {
            get {
                return ResourceManager.GetString("Common_AnswerRequiredErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Confirm Password"".
        /// </summary>
        public static string Common_ConfirmPasswordLabelText {
            get {
                return ResourceManager.GetString("Common_ConfirmPasswordLabelText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Passwords do not match!"".
        /// </summary>
        public static string Common_ConfirmPasswordNotMatchErrorMessage {
            get {
                return ResourceManager.GetString("Common_ConfirmPasswordNotMatchErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Confirm Password is required."".
        /// </summary>
        public static string Common_ConfirmPasswordRequiredErrorMessage {
            get {
                return ResourceManager.GetString("Common_ConfirmPasswordRequiredErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Email format is not correct."".
        /// </summary>
        public static string Common_EmailFormatErrorMessage {
            get {
                return ResourceManager.GetString("Common_EmailFormatErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Email"".
        /// </summary>
        public static string Common_EmailLabelText {
            get {
                return ResourceManager.GetString("Common_EmailLabelText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Email is required."".
        /// </summary>
        public static string Common_EmailRequiredErrorMessage {
            get {
                return ResourceManager.GetString("Common_EmailRequiredErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Current Password:"".
        /// </summary>
        public static string Common_CurrentPasswordLabelText {
            get {
                return ResourceManager.GetString("Common_CurrentPasswordLabelText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "New Password:"".
        /// </summary>
        public static string Common_NewPasswordLabelText {
            get {
                return ResourceManager.GetString("Common_NewPasswordLabelText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Password"".
        /// </summary>
        public static string Common_PasswordLabelText {
            get {
                return ResourceManager.GetString("Common_PasswordLabelText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Password is required."".
        /// </summary>
        public static string Common_PasswordRequiredErrorMessage {
            get {
                return ResourceManager.GetString("Common_PasswordRequiredErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Password length: 6-20 characters."".
        /// </summary>
        public static string Common_PasswordLengthErrorMessage {
            get {
                return ResourceManager.GetString("Common_PasswordLengthErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The {0} must be at least {2} characters long."".
        /// </summary>
        public static string Common_PasswordErrorMessage {
            get {
                return ResourceManager.GetString("Common_PasswordErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Question:"".
        /// </summary>
        public static string Common_QuestionLabelText {
            get {
                return ResourceManager.GetString("Common_QuestionLabelText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Question is required."".
        /// </summary>
        public static string Common_QuestionRequiredErrorMessage {
            get {
                return ResourceManager.GetString("Common_QuestionRequiredErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Submit"".
        /// </summary>
        public static string Common_SubmitValue {
            get {
                return ResourceManager.GetString("Common_SubmitValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "User Name:"".
        /// </summary>
        public static string Common_UserNameLabelText {
            get {
                return ResourceManager.GetString("Common_UserNameLabelText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "User Name is required."".
        /// </summary>
        public static string Common_UserNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("Common_UserNameRequiredErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Welcome to nTier on Time."".
        /// </summary>
        public static string Common_WelcomeToNTIERONTIME {
            get {
                return ResourceManager.GetString("Common_WelcomeToNTIERONTIME", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "About"".
        /// </summary>
        public static string Common_AboutPageTitle {
            get {
                return ResourceManager.GetString("Common_AboutPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Contacts"".
        /// </summary>
        public static string Common_ContactPageTitle {
            get {
                return ResourceManager.GetString("Common_ContactPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "No data was returned."".
        /// </summary>
        public static string Common_Nodatawasreturned {
            get {
                return ResourceManager.GetString("Common_Nodatawasreturned", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Home"".
        /// </summary>
        public static string Common_Url_Home {
            get {
                return ResourceManager.GetString("Common_Url_Home", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "About"".
        /// </summary>
        public static string Common_Url_About {
            get {
                return ResourceManager.GetString("Common_Url_About", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Contact"".
        /// </summary>
        public static string Common_Url_Contact {
            get {
                return ResourceManager.GetString("Common_Url_Contact", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Welcome"".
        /// </summary>
        public static string Common_Welcome {
            get {
                return ResourceManager.GetString("Common_Welcome", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Workspaces"".
        /// </summary>
        public static string Common_Workspaces {
            get {
                return ResourceManager.GetString("Common_Workspaces", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Filter"".
        /// </summary>
        public static string Common_Filter {
            get {
                return ResourceManager.GetString("Common_Filter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Phone"".
        /// </summary>
        public static string Contact_PhoneText {
            get {
                return ResourceManager.GetString("Contact_PhoneText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Address"".
        /// </summary>
        public static string Contact_AddressText {
            get {
                return ResourceManager.GetString("Contact_AddressText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Email"".
        /// </summary>
        public static string Contact_EmailText {
            get {
                return ResourceManager.GetString("Contact_EmailText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Home Page"".
        /// </summary>
        public static string Home_TitleText {
            get {
                return ResourceManager.GetString("Home_TitleText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Home Page"".
        /// </summary>
        public static string Home_DescriptionText {
            get {
                return ResourceManager.GetString("Home_DescriptionText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Error"".
        /// </summary>
        public static string Error_TitleText {
            get {
                return ResourceManager.GetString("Error_TitleText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "An error occurred while processing your request."".
        /// </summary>
        public static string Error_DescriptionText {
            get {
                return ResourceManager.GetString("Error_DescriptionText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Are you sure you want to delete this?"".
        /// </summary>
        public static string Warning_Areyousureyouwanttodeletethis {
            get {
                return ResourceManager.GetString("Warning_Areyousureyouwanttodeletethis", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Workspace"".
        /// </summary>
        public static string Workspace_DescriptionText {
            get {
                return ResourceManager.GetString("Workspace_DescriptionText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "On"".
        /// </summary>
        public static string On_DescriptionText {
            get {
                return ResourceManager.GetString("On_DescriptionText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Off"".
        /// </summary>
        public static string Off_DescriptionText {
            get {
                return ResourceManager.GetString("Off_DescriptionText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Items Per Page"".
        /// </summary>
        public static string Common_Pagination_ItemsPerPage {
            get {
                return ResourceManager.GetString("Common_Pagination_ItemsPerPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Sort By"".
        /// </summary>
        public static string Common_Pagination_SortBy {
            get {
                return ResourceManager.GetString("Common_Pagination_SortBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "You can import .csv and .xlsx with first heading row in following format:"".
        /// </summary>
        public static string Data_Import_DescriptionText {
            get {
                return ResourceManager.GetString("Data_Import_DescriptionText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Data Import Success"".
        /// </summary>
        public static string Data_Import_Success {
            get {
                return ResourceManager.GetString("Data_Import_Success", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "No Record In Source File"".
        /// </summary>
        public static string Data_Import_NoRecordInSourceFile {
            get {
                return ResourceManager.GetString("Data_Import_NoRecordInSourceFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "File Format or File Content is wrong"".
        /// </summary>
        public static string Data_Import_Notaproperfile {
            get {
                return ResourceManager.GetString("Data_Import_Notaproperfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Received"".
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Pending"".
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "BeingProcessed"".
        /// </summary>
        public static string BeingProcessed {
            get {
                return ResourceManager.GetString("BeingProcessed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Rejected"".
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Accepted"".
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Succeeded"".
        /// </summary>
        public static string Succeeded {
            get {
                return ResourceManager.GetString("Succeeded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "OnHold"".
        /// </summary>
        public static string OnHold {
            get {
                return ResourceManager.GetString("OnHold", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Failed"".
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Request Error"".
        /// </summary>
        public static string RequestError {
            get {
                return ResourceManager.GetString("RequestError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Message OK"".
        /// </summary>
        public static string MessageOK {
            get {
                return ResourceManager.GetString("MessageOK", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "No Value From DataSource"".
        /// </summary>
        public static string NoValueFromDataSource {
            get {
                return ResourceManager.GetString("NoValueFromDataSource", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Message Error Detected"".
        /// </summary>
        public static string MessageErrorDetected {
            get {
                return ResourceManager.GetString("MessageErrorDetected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "You Have No Permission To View"".
        /// </summary>
        public static string YouHaveNoPermissionToView {
            get {
                return ResourceManager.GetString("YouHaveNoPermissionToView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "You Have NoPermissionTo Insert"".
        /// </summary>
        public static string YouHaveNoPermissionToInsert {
            get {
                return ResourceManager.GetString("YouHaveNoPermissionToInsert", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "You Have No Permission To Update"".
        /// </summary>
        public static string YouHaveNoPermissionToUpdate {
            get {
                return ResourceManager.GetString("YouHaveNoPermissionToUpdate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "You Have No Permission To Delete"".
        /// </summary>
        public static string YouHaveNoPermissionToDelete {
            get {
                return ResourceManager.GetString("YouHaveNoPermissionToDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Items per page : "".
        /// </summary>
        public static string Pagination_ItemsPerPage {
            get {
                return ResourceManager.GetString("Pagination_ItemsPerPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Sort By"".
        /// </summary>
        public static string Pagination_SortBy {
            get {
                return ResourceManager.GetString("Pagination_SortBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "0 Record in Current Page"".
        /// </summary>
        public static string Pagination_NoData {
            get {
                return ResourceManager.GetString("Pagination_NoData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Page# {5} out of {4}. {0} Records: ({1} - {2}) out of {3}"".
        /// </summary>
        public static string Pagination_PagingInformation {
            get {
                return ResourceManager.GetString("Pagination_PagingInformation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Menu"".
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Quit"".
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Quit Application"".
        /// </summary>
        public static string QuitApplication {
            get {
                return ResourceManager.GetString("QuitApplication", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Do you want to quit application?"".
        /// </summary>
        public static string QuitApplicationMessage {
            get {
                return ResourceManager.GetString("QuitApplicationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Unknown"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_Unknown {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_Unknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Custom"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_Custom {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_Custom", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Last Ten Years"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_LastTenYears {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_LastTenYears", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Last Five Years"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_LastFiveYears {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_LastFiveYears", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Last Year"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_LastYear {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_LastYear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Last Six Months"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_LastSixMonths {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_LastSixMonths", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Last Three Months"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_LastThreeMonths {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_LastThreeMonths", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Last Month"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_LastMonth {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_LastMonth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Last Week"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_LastWeek {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_LastWeek", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Yesterday"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_Yesterday {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_Yesterday", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "This Year"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_ThisYear {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_ThisYear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "This Month"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_ThisMonth {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_ThisMonth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "This Week"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_ThisWeek {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_ThisWeek", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Today"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_Today {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_Today", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tomorrow"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_Tomorrow {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_Tomorrow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Next Week"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_NextWeek {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_NextWeek", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Next Month"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_NextMonth {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_NextMonth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Next Three Months"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_NextThreeMonths {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_NextThreeMonths", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Next Six Months"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_NextSixMonths {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_NextSixMonths", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Next Year"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_NextYear {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_NextYear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Next Five Years"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_NextFiveYears {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_NextFiveYears", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Next Ten Years"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_NextTenYears {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_NextTenYears", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "All"".
        /// </summary>
        public static string PredefinedBooleanSelectedValues_All {
            get {
                return ResourceManager.GetString("PredefinedBooleanSelectedValues_All", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "True"".
        /// </summary>
        public static string PredefinedBooleanSelectedValues_True {
            get {
                return ResourceManager.GetString("PredefinedBooleanSelectedValues_True", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "False"".
        /// </summary>
        public static string PredefinedBooleanSelectedValues_False {
            get {
                return ResourceManager.GetString("PredefinedBooleanSelectedValues_False", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "From"".
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "To"".
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "-- All --"".
        /// </summary>
        public static string AllCaption {
            get {
                return ResourceManager.GetString("AllCaption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "-- Select --"".
        /// </summary>
        public static string SelectCaption {
            get {
                return ResourceManager.GetString("SelectCaption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Add New"".
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Attachment"".
        /// </summary>
        public static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Back"".
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Bookmark"".
        /// </summary>
        public static string Bookmark {
            get {
                return ResourceManager.GetString("Bookmark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Calendar"".
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Cancel"".
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Change Password"".
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Chart"".
        /// </summary>
        public static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Checked"".
        /// </summary>
        public static string Checkbox_Checked {
            get {
                return ResourceManager.GetString("Checkbox_Checked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Unchecked"".
        /// </summary>
        public static string Checkbox_Unchecked {
            get {
                return ResourceManager.GetString("Checkbox_Unchecked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Clock"".
        /// </summary>
        public static string Clock {
            get {
                return ResourceManager.GetString("Clock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Close"".
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Comment"".
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Comments"".
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Confirm"".
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Copy"".
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Create User"".
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Delete"".
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Details"".
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Down"".
        /// </summary>
        public static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Download"".
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Edit"".
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Exit"".
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Export"".
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Export To Excel"".
        /// </summary>
        public static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Favorite"".
        /// </summary>
        public static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "File Replace"".
        /// </summary>
        public static string FileReplace {
            get {
                return ResourceManager.GetString("FileReplace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "First"".
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Forward"".
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Full Details"".
        /// </summary>
        public static string FullDetails {
            get {
                return ResourceManager.GetString("FullDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Go"".
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Goto Search"".
        /// </summary>
        public static string GotoSearch {
            get {
                return ResourceManager.GetString("GotoSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Heart"".
        /// </summary>
        public static string Heart {
            get {
                return ResourceManager.GetString("Heart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Help"".
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Home"".
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Import"".
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Index"".
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Information"".
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Insert"".
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Last"".
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Load File"".
        /// </summary>
        public static string LoadFile {
            get {
                return ResourceManager.GetString("LoadFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Lock"".
        /// </summary>
        public static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Mail"".
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Mail Lock"".
        /// </summary>
        public static string MailLock {
            get {
                return ResourceManager.GetString("MailLock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Mail Receive"".
        /// </summary>
        public static string MailReceive {
            get {
                return ResourceManager.GetString("MailReceive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Mail Search"".
        /// </summary>
        public static string MailSearch {
            get {
                return ResourceManager.GetString("MailSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Mail Send"".
        /// </summary>
        public static string MailSend {
            get {
                return ResourceManager.GetString("MailSend", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Minus"".
        /// </summary>
        public static string Minus {
            get {
                return ResourceManager.GetString("Minus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Money"".
        /// </summary>
        public static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "More"".
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "New File"".
        /// </summary>
        public static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Next"".
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Numeric Down"".
        /// </summary>
        public static string NumericDown {
            get {
                return ResourceManager.GetString("NumericDown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Numeric Up"".
        /// </summary>
        public static string NumericUp {
            get {
                return ResourceManager.GetString("NumericUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Open"".
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Page Size"".
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Password Recovery"".
        /// </summary>
        public static string PasswordRecovery {
            get {
                return ResourceManager.GetString("PasswordRecovery", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Paste"".
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Pause"".
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Pie Chart"".
        /// </summary>
        public static string PieChart {
            get {
                return ResourceManager.GetString("PieChart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Play"".
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Plus"".
        /// </summary>
        public static string Plus {
            get {
                return ResourceManager.GetString("Plus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Previous"".
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Process"".
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Promotion"".
        /// </summary>
        public static string Promotion {
            get {
                return ResourceManager.GetString("Promotion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Protection"".
        /// </summary>
        public static string Protection {
            get {
                return ResourceManager.GetString("Protection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Question"".
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Record"".
        /// </summary>
        public static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Recycle"".
        /// </summary>
        public static string Recycle {
            get {
                return ResourceManager.GetString("Recycle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Redo"".
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Refresh"".
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Register"".
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Repeat"".
        /// </summary>
        public static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Results"".
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Rss"".
        /// </summary>
        public static string Rss {
            get {
                return ResourceManager.GetString("Rss", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Save"".
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Search"".
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Search Page"".
        /// </summary>
        public static string SearchPage {
            get {
                return ResourceManager.GetString("SearchPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Setting"".
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Shopping Cart"".
        /// </summary>
        public static string ShoppingCart {
            get {
                return ResourceManager.GetString("ShoppingCart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Sign Up"".
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Stop"".
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tag Blue"".
        /// </summary>
        public static string TagBlue {
            get {
                return ResourceManager.GetString("TagBlue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tag Green"".
        /// </summary>
        public static string TagGreen {
            get {
                return ResourceManager.GetString("TagGreen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Text Page"".
        /// </summary>
        public static string TextPage {
            get {
                return ResourceManager.GetString("TextPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Title"".
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Checked"".
        /// </summary>
        public static string ToggleButton_Checked {
            get {
                return ResourceManager.GetString("ToggleButton_Checked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Unchecked"".
        /// </summary>
        public static string ToggleButton_Unchecked {
            get {
                return ResourceManager.GetString("ToggleButton_Unchecked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tutorial"".
        /// </summary>
        public static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Undo"".
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Unlock"".
        /// </summary>
        public static string Unlock {
            get {
                return ResourceManager.GetString("Unlock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Up"".
        /// </summary>
        public static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Update"".
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "User"".
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Users"".
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Warning"".
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Zoom In"".
        /// </summary>
        public static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Zoom Out"".
        /// </summary>
        public static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }

    }
}

